apiVersion: apps/v1
kind: Deployment
metadata:
  name: functional-test
  labels:
    app: functional-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: functional-test
  template:
    metadata:
      labels:
        app: functional-test
    spec:
      containers:
      - name: functional-test
        image: gcr.io/magnetic-port-293211/functional-test:v31
