apiVersion: apps/v1
kind: Deployment
metadata:
  name: request-sender
  labels:
    app: request-sender
spec:
  replicas: 3
  selector:
    matchLabels:
      app: request-sender
  template:
    metadata:
      labels:
        app: request-sender
    spec:
      containers:
      - name: request-sender
        image: gcr.io/magnetic-port-293211/request-sender:v5
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5

