apiVersion: apps/v1
kind: Deployment
metadata:
  name: fake-service
  labels:
    app: fake-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fake-service
  template:
    metadata:
      labels:
        app: fake-service
    spec:
      containers:
      - name: fake-service
        image: gcr.io/magnetic-port-293211/fake-service:v1
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5

