apiVersion: v1
kind: Service
metadata:
  name: fake-service-service
spec:
  type: LoadBalancer
  ports:
    - name: http-port
      port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: fake-service
